-- Browser-friendly source links for the China Section 301 and Section 232
-- metals rows (seeded in 20261002234639). USITC serves the HTS Chapter 99 PDF
-- only as a download, so each row's primary link becomes the HTS website's
-- search for its heading (or the Federal Register notice it cites), and the
-- PDF becomes a labelled download link with the page of the heading's row.
-- Changes no rates or scope, so programs keep their review status.
--
-- Generated by scripts/tariff/extract-2b.mjs + generate-seeds.mjs from
-- data/tariff/2b-china301-232/source-links.json; do not edit by hand. A row
-- whose link a tariff editor has already changed is left alone.

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.01',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.88.01'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.01'
  and effective_from = '2018-07-06' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.02',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.88.02'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.02'
  and effective_from = '2018-08-23' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.03',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 686 (99-III-514), heading 9903.88.03'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.03'
  and effective_from = '2019-05-10' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.04',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 686 (99-III-514), heading 9903.88.04'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.04'
  and effective_from = '2019-05-10' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.15',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 687 (99-III-515), heading 9903.88.15'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.15'
  and effective_from = '2020-02-14' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.01',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.01'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.01'
  and effective_from = '2024-09-27' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.02',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.02'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.02'
  and effective_from = '2024-09-27' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.03',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.03'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.03'
  and effective_from = '2024-09-27' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.05',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.05'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.05'
  and effective_from = '2025-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.06',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.06'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.06'
  and effective_from = '2026-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.07',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 699 (99-III-527), heading 9903.91.07'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.07'
  and effective_from = '2026-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.08',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 700 (99-III-528), heading 9903.91.08'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.08'
  and effective_from = '2026-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.11',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 700 (99-III-528), heading 9903.91.11'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.11'
  and effective_from = '2025-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.92.10',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 702 (99-III-530), heading 9903.92.10'
where program_key = 'section_301_china' and chapter99_heading = '9903.92.10'
  and effective_from = '2024-09-27' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.12',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 700 (99-III-528), heading 9903.91.12'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.12'
  and effective_from = '2026-11-10' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.91.14',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 701 (99-III-529), heading 9903.91.14'
where program_key = 'section_301_china' and chapter99_heading = '9903.91.14'
  and effective_from = '2026-11-10' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.69',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 694 (99-III-522), heading 9903.88.69'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.69'
  and effective_from = '2024-06-15' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.88.70',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 694 (99-III-522), heading 9903.88.70'
where program_key = 'section_301_china' and chapter99_heading = '9903.88.70'
  and effective_from = '2024-01-01' and origin_countries is not distinct from array['CN']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.02',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 681 (99-III-509), heading 9903.82.02'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.02'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.09',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.09'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.09'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.10',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.10'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.10'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.12',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.12'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.12'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['BY','CU','KP','RU']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.14',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.14'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.14'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.16',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.16'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.16'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.17',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.17'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.17'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.04',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.04'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.04'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['GB']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.05',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.05'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.05'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['GB']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.06',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.06'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.06'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.07',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.07'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.07'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.15',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.15'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.15'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.23',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.23'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.23'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.25',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.25'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.25'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.03',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 682 (99-III-510), heading 9903.82.03'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.03'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.01',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 681 (99-III-509), heading 9903.82.01'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.01'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.13',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 683 (99-III-511), heading 9903.82.13'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.13'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.18',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.18'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.18'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['CA','MX']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.19',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.19'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.19'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['CA','MX']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.21',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.21'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.21'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['CA','MX']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.96.01',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 707 (99-III-535), heading 9903.96.01'
where program_key = 'section_232_metals' and chapter99_heading = '9903.96.01'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['GB']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.96.02',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 707 (99-III-535), heading 9903.96.02'
where program_key = 'section_232_metals' and chapter99_heading = '9903.96.02'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['JP']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.96.03',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 707 (99-III-535), heading 9903.96.03'
where program_key = 'section_232_metals' and chapter99_heading = '9903.96.03'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['TW']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://www.federalregister.gov/documents/2026/04/09/2026-06960/strengthening-actions-taken-to-adjust-imports-of-aluminum-steel-and-copper-into-the-united-states',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.85.67'
where program_key = 'section_232_metals' and chapter99_heading = '9903.85.67'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://www.federalregister.gov/documents/2026/04/09/2026-06960/strengthening-actions-taken-to-adjust-imports-of-aluminum-steel-and-copper-into-the-united-states';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.85.67',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.85.67'
where program_key = 'section_232_metals' and chapter99_heading = '9903.85.67'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://www.federalregister.gov/documents/2026/04/09/2026-06960/strengthening-actions-taken-to-adjust-imports-of-aluminum-steel-and-copper-into-the-united-states',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.85.68'
where program_key = 'section_232_metals' and chapter99_heading = '9903.85.68'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['RU']
  and source_url = 'https://www.federalregister.gov/documents/2026/04/09/2026-06960/strengthening-actions-taken-to-adjust-imports-of-aluminum-steel-and-copper-into-the-united-states';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.85.68',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 685 (99-III-513), heading 9903.85.68'
where program_key = 'section_232_metals' and chapter99_heading = '9903.85.68'
  and effective_from = '2026-06-08' and origin_countries is not distinct from null
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';

update additional_duties
set source_url = 'https://hts.usitc.gov/search?query=9903.82.22',
  source_document_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099',
  source_document_label = 'Download Chapter 99 PDF, 2026 Rev. 20 (14 MB) — see page 684 (99-III-512), heading 9903.82.22'
where program_key = 'section_232_metals' and chapter99_heading = '9903.82.22'
  and effective_from = '2026-06-08' and origin_countries is not distinct from array['AR','AT','BE','BG','CH','CY','CZ','DE','DK','EC','EE','ES','FI','FR','GB','GR','GT','HR','HU','IE','IT','JP','KR','LI','LT','LU','LV','MT','NL','PL','PT','RO','SE','SI','SK','SV','TW']
  and source_url = 'https://hts.usitc.gov/reststop/file?release=2026HTSRev20&filename=Chapter%2099';
